name: Sync Workflow
on:
  workflow_dispatch:

permissions: write-all
jobs:
  sync:
    name: Sync krkn-hub to the upstream repo
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Sync with GH CLI
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh repo sync redhat-chaos/krkn-hub -b main
